/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Client Lead CRM API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DashboardStats,
  HealthStatus,
  Lead,
  LeadInput,
  LeadStatusUpdate,
  LeadUpdate,
  LeadWithNotes,
  ListLeadsParams,
  Note,
  NoteInput,
  NoteUpdate
} from './api.schemas';

import { customFetch } from '../custom-fetch';
import type { ErrorType , BodyType } from '../custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getHealthCheckUrl = () => {




  return `/api/healthz`
}

/**
 * @summary Health check
 */
export const healthCheck = async ( options?: RequestInit): Promise<HealthStatus> => {

  return customFetch<HealthStatus>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/api/healthz`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = ErrorType<unknown>


/**
 * @summary Health check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListLeadsUrl = (params?: ListLeadsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/leads?${stringifiedParams}` : `/api/leads`
}

/**
 * @summary List all leads
 */
export const listLeads = async (params?: ListLeadsParams, options?: RequestInit): Promise<Lead[]> => {

  return customFetch<Lead[]>(getListLeadsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListLeadsQueryKey = (params?: ListLeadsParams,) => {
    return [
    `/api/leads`, ...(params ? [params] : [])
    ] as const;
    }


export const getListLeadsQueryOptions = <TData = Awaited<ReturnType<typeof listLeads>>, TError = ErrorType<unknown>>(params?: ListLeadsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listLeads>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListLeadsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listLeads>>> = ({ signal }) => listLeads(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listLeads>>, TError, TData> & { queryKey: QueryKey }
}

export type ListLeadsQueryResult = NonNullable<Awaited<ReturnType<typeof listLeads>>>
export type ListLeadsQueryError = ErrorType<unknown>


/**
 * @summary List all leads
 */

export function useListLeads<TData = Awaited<ReturnType<typeof listLeads>>, TError = ErrorType<unknown>>(
 params?: ListLeadsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listLeads>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListLeadsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCreateLeadUrl = () => {




  return `/api/leads`
}

/**
 * @summary Create a new lead
 */
export const createLead = async (leadInput: LeadInput, options?: RequestInit): Promise<Lead> => {

  return customFetch<Lead>(getCreateLeadUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      leadInput,)
  }
);}




export const getCreateLeadMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLead>>, TError,{data: BodyType<LeadInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createLead>>, TError,{data: BodyType<LeadInput>}, TContext> => {

const mutationKey = ['createLead'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createLead>>, {data: BodyType<LeadInput>}> = (props) => {
          const {data} = props ?? {};

          return  createLead(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateLeadMutationResult = NonNullable<Awaited<ReturnType<typeof createLead>>>
    export type CreateLeadMutationBody = BodyType<LeadInput>
    export type CreateLeadMutationError = ErrorType<unknown>

    /**
 * @summary Create a new lead
 */
export const useCreateLead = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLead>>, TError,{data: BodyType<LeadInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createLead>>,
        TError,
        {data: BodyType<LeadInput>},
        TContext
      > => {
      return useMutation(getCreateLeadMutationOptions(options));
    }

export const getGetLeadUrl = (id: number,) => {




  return `/api/leads/${id}`
}

/**
 * @summary Get a lead by ID
 */
export const getLead = async (id: number, options?: RequestInit): Promise<LeadWithNotes> => {

  return customFetch<LeadWithNotes>(getGetLeadUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLeadQueryKey = (id: number,) => {
    return [
    `/api/leads/${id}`
    ] as const;
    }


export const getGetLeadQueryOptions = <TData = Awaited<ReturnType<typeof getLead>>, TError = ErrorType<void>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getLead>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLeadQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLead>>> = ({ signal }) => getLead(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLead>>, TError, TData> & { queryKey: QueryKey }
}

export type GetLeadQueryResult = NonNullable<Awaited<ReturnType<typeof getLead>>>
export type GetLeadQueryError = ErrorType<void>


/**
 * @summary Get a lead by ID
 */

export function useGetLead<TData = Awaited<ReturnType<typeof getLead>>, TError = ErrorType<void>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getLead>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetLeadQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getUpdateLeadUrl = (id: number,) => {




  return `/api/leads/${id}`
}

/**
 * @summary Update a lead
 */
export const updateLead = async (id: number,
    leadUpdate: LeadUpdate, options?: RequestInit): Promise<Lead> => {

  return customFetch<Lead>(getUpdateLeadUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      leadUpdate,)
  }
);}




export const getUpdateLeadMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLead>>, TError,{id: number;data: BodyType<LeadUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateLead>>, TError,{id: number;data: BodyType<LeadUpdate>}, TContext> => {

const mutationKey = ['updateLead'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateLead>>, {id: number;data: BodyType<LeadUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateLead(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateLeadMutationResult = NonNullable<Awaited<ReturnType<typeof updateLead>>>
    export type UpdateLeadMutationBody = BodyType<LeadUpdate>
    export type UpdateLeadMutationError = ErrorType<void>

    /**
 * @summary Update a lead
 */
export const useUpdateLead = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLead>>, TError,{id: number;data: BodyType<LeadUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateLead>>,
        TError,
        {id: number;data: BodyType<LeadUpdate>},
        TContext
      > => {
      return useMutation(getUpdateLeadMutationOptions(options));
    }

export const getDeleteLeadUrl = (id: number,) => {




  return `/api/leads/${id}`
}

/**
 * @summary Delete a lead
 */
export const deleteLead = async (id: number, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeleteLeadUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteLeadMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLead>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteLead>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteLead'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteLead>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteLead(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteLeadMutationResult = NonNullable<Awaited<ReturnType<typeof deleteLead>>>

    export type DeleteLeadMutationError = ErrorType<unknown>

    /**
 * @summary Delete a lead
 */
export const useDeleteLead = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLead>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteLead>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteLeadMutationOptions(options));
    }

export const getUpdateLeadStatusUrl = (id: number,) => {




  return `/api/leads/${id}/status`
}

/**
 * @summary Update a lead's status
 */
export const updateLeadStatus = async (id: number,
    leadStatusUpdate: LeadStatusUpdate, options?: RequestInit): Promise<Lead> => {

  return customFetch<Lead>(getUpdateLeadStatusUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      leadStatusUpdate,)
  }
);}




export const getUpdateLeadStatusMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLeadStatus>>, TError,{id: number;data: BodyType<LeadStatusUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateLeadStatus>>, TError,{id: number;data: BodyType<LeadStatusUpdate>}, TContext> => {

const mutationKey = ['updateLeadStatus'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateLeadStatus>>, {id: number;data: BodyType<LeadStatusUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateLeadStatus(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateLeadStatusMutationResult = NonNullable<Awaited<ReturnType<typeof updateLeadStatus>>>
    export type UpdateLeadStatusMutationBody = BodyType<LeadStatusUpdate>
    export type UpdateLeadStatusMutationError = ErrorType<void>

    /**
 * @summary Update a lead's status
 */
export const useUpdateLeadStatus = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLeadStatus>>, TError,{id: number;data: BodyType<LeadStatusUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateLeadStatus>>,
        TError,
        {id: number;data: BodyType<LeadStatusUpdate>},
        TContext
      > => {
      return useMutation(getUpdateLeadStatusMutationOptions(options));
    }

export const getListNotesUrl = (id: number,) => {




  return `/api/leads/${id}/notes`
}

/**
 * @summary List notes for a lead
 */
export const listNotes = async (id: number, options?: RequestInit): Promise<Note[]> => {

  return customFetch<Note[]>(getListNotesUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListNotesQueryKey = (id: number,) => {
    return [
    `/api/leads/${id}/notes`
    ] as const;
    }


export const getListNotesQueryOptions = <TData = Awaited<ReturnType<typeof listNotes>>, TError = ErrorType<unknown>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listNotes>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListNotesQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listNotes>>> = ({ signal }) => listNotes(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listNotes>>, TError, TData> & { queryKey: QueryKey }
}

export type ListNotesQueryResult = NonNullable<Awaited<ReturnType<typeof listNotes>>>
export type ListNotesQueryError = ErrorType<unknown>


/**
 * @summary List notes for a lead
 */

export function useListNotes<TData = Awaited<ReturnType<typeof listNotes>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listNotes>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListNotesQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCreateNoteUrl = (id: number,) => {




  return `/api/leads/${id}/notes`
}

/**
 * @summary Add a note to a lead
 */
export const createNote = async (id: number,
    noteInput: NoteInput, options?: RequestInit): Promise<Note> => {

  return customFetch<Note>(getCreateNoteUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      noteInput,)
  }
);}




export const getCreateNoteMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createNote>>, TError,{id: number;data: BodyType<NoteInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createNote>>, TError,{id: number;data: BodyType<NoteInput>}, TContext> => {

const mutationKey = ['createNote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createNote>>, {id: number;data: BodyType<NoteInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  createNote(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateNoteMutationResult = NonNullable<Awaited<ReturnType<typeof createNote>>>
    export type CreateNoteMutationBody = BodyType<NoteInput>
    export type CreateNoteMutationError = ErrorType<unknown>

    /**
 * @summary Add a note to a lead
 */
export const useCreateNote = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createNote>>, TError,{id: number;data: BodyType<NoteInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createNote>>,
        TError,
        {id: number;data: BodyType<NoteInput>},
        TContext
      > => {
      return useMutation(getCreateNoteMutationOptions(options));
    }

export const getUpdateNoteUrl = (noteId: number,) => {




  return `/api/notes/${noteId}`
}

/**
 * @summary Update a note
 */
export const updateNote = async (noteId: number,
    noteUpdate: NoteUpdate, options?: RequestInit): Promise<Note> => {

  return customFetch<Note>(getUpdateNoteUrl(noteId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      noteUpdate,)
  }
);}




export const getUpdateNoteMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateNote>>, TError,{noteId: number;data: BodyType<NoteUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateNote>>, TError,{noteId: number;data: BodyType<NoteUpdate>}, TContext> => {

const mutationKey = ['updateNote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateNote>>, {noteId: number;data: BodyType<NoteUpdate>}> = (props) => {
          const {noteId,data} = props ?? {};

          return  updateNote(noteId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateNoteMutationResult = NonNullable<Awaited<ReturnType<typeof updateNote>>>
    export type UpdateNoteMutationBody = BodyType<NoteUpdate>
    export type UpdateNoteMutationError = ErrorType<unknown>

    /**
 * @summary Update a note
 */
export const useUpdateNote = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateNote>>, TError,{noteId: number;data: BodyType<NoteUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateNote>>,
        TError,
        {noteId: number;data: BodyType<NoteUpdate>},
        TContext
      > => {
      return useMutation(getUpdateNoteMutationOptions(options));
    }

export const getDeleteNoteUrl = (noteId: number,) => {




  return `/api/notes/${noteId}`
}

/**
 * @summary Delete a note
 */
export const deleteNote = async (noteId: number, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeleteNoteUrl(noteId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteNoteMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNote>>, TError,{noteId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteNote>>, TError,{noteId: number}, TContext> => {

const mutationKey = ['deleteNote'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteNote>>, {noteId: number}> = (props) => {
          const {noteId} = props ?? {};

          return  deleteNote(noteId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteNoteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteNote>>>

    export type DeleteNoteMutationError = ErrorType<unknown>

    /**
 * @summary Delete a note
 */
export const useDeleteNote = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNote>>, TError,{noteId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteNote>>,
        TError,
        {noteId: number},
        TContext
      > => {
      return useMutation(getDeleteNoteMutationOptions(options));
    }

export const getGetDashboardStatsUrl = () => {




  return `/api/dashboard/stats`
}

/**
 * @summary Get CRM dashboard stats
 */
export const getDashboardStats = async ( options?: RequestInit): Promise<DashboardStats> => {

  return customFetch<DashboardStats>(getGetDashboardStatsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDashboardStatsQueryKey = () => {
    return [
    `/api/dashboard/stats`
    ] as const;
    }


export const getGetDashboardStatsQueryOptions = <TData = Awaited<ReturnType<typeof getDashboardStats>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDashboardStats>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardStatsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardStats>>> = ({ signal }) => getDashboardStats({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDashboardStats>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDashboardStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboardStats>>>
export type GetDashboardStatsQueryError = ErrorType<unknown>


/**
 * @summary Get CRM dashboard stats
 */

export function useGetDashboardStats<TData = Awaited<ReturnType<typeof getDashboardStats>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDashboardStats>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetDashboardStatsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetRecentLeadsUrl = () => {




  return `/api/dashboard/recent`
}

/**
 * @summary Get recently added or updated leads
 */
export const getRecentLeads = async ( options?: RequestInit): Promise<Lead[]> => {

  return customFetch<Lead[]>(getGetRecentLeadsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetRecentLeadsQueryKey = () => {
    return [
    `/api/dashboard/recent`
    ] as const;
    }


export const getGetRecentLeadsQueryOptions = <TData = Awaited<ReturnType<typeof getRecentLeads>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRecentLeads>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRecentLeadsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRecentLeads>>> = ({ signal }) => getRecentLeads({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRecentLeads>>, TError, TData> & { queryKey: QueryKey }
}

export type GetRecentLeadsQueryResult = NonNullable<Awaited<ReturnType<typeof getRecentLeads>>>
export type GetRecentLeadsQueryError = ErrorType<unknown>


/**
 * @summary Get recently added or updated leads
 */

export function useGetRecentLeads<TData = Awaited<ReturnType<typeof getRecentLeads>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRecentLeads>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetRecentLeadsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







