/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Client Lead CRM API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export type LeadStatus = typeof LeadStatus[keyof typeof LeadStatus];


export const LeadStatus = {
  new: 'new',
  contacted: 'contacted',
  converted: 'converted',
  lost: 'lost',
} as const;

export interface Lead {
  id: number;
  name: string;
  email: string;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  company?: string | null;
  source: string;
  status: LeadStatus;
  /** @nullable */
  notes?: string | null;
  createdAt: string;
  updatedAt: string;
}

export type LeadWithNotesStatus = typeof LeadWithNotesStatus[keyof typeof LeadWithNotesStatus];


export const LeadWithNotesStatus = {
  new: 'new',
  contacted: 'contacted',
  converted: 'converted',
  lost: 'lost',
} as const;

export interface Note {
  id: number;
  leadId: number;
  content: string;
  /** @nullable */
  followUpDate?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface LeadWithNotes {
  id: number;
  name: string;
  email: string;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  company?: string | null;
  source: string;
  status: LeadWithNotesStatus;
  /** @nullable */
  notes?: string | null;
  createdAt: string;
  updatedAt: string;
  leadNotes: Note[];
}

export type LeadInputStatus = typeof LeadInputStatus[keyof typeof LeadInputStatus];


export const LeadInputStatus = {
  new: 'new',
  contacted: 'contacted',
  converted: 'converted',
  lost: 'lost',
} as const;

export interface LeadInput {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  email: string;
  phone?: string;
  company?: string;
  /** @minLength 1 */
  source: string;
  status?: LeadInputStatus;
  notes?: string;
}

export type LeadUpdateStatus = typeof LeadUpdateStatus[keyof typeof LeadUpdateStatus];


export const LeadUpdateStatus = {
  new: 'new',
  contacted: 'contacted',
  converted: 'converted',
  lost: 'lost',
} as const;

export interface LeadUpdate {
  /** @minLength 1 */
  name?: string;
  /** @minLength 1 */
  email?: string;
  phone?: string;
  company?: string;
  source?: string;
  status?: LeadUpdateStatus;
  notes?: string;
}

export type LeadStatusUpdateStatus = typeof LeadStatusUpdateStatus[keyof typeof LeadStatusUpdateStatus];


export const LeadStatusUpdateStatus = {
  new: 'new',
  contacted: 'contacted',
  converted: 'converted',
  lost: 'lost',
} as const;

export interface LeadStatusUpdate {
  status: LeadStatusUpdateStatus;
}

export interface NoteInput {
  /** @minLength 1 */
  content: string;
  followUpDate?: string;
}

export interface NoteUpdate {
  /** @minLength 1 */
  content?: string;
  followUpDate?: string;
}

export type DashboardStatsByStatus = {
  new: number;
  contacted: number;
  converted: number;
  lost: number;
};

export type DashboardStatsBySourceItem = {
  source: string;
  count: number;
};

export interface DashboardStats {
  totalLeads: number;
  byStatus: DashboardStatsByStatus;
  conversionRate: number;
  recentCount: number;
  bySource?: DashboardStatsBySourceItem[];
}

export type ListLeadsParams = {
status?: ListLeadsStatus;
source?: string;
search?: string;
};

export type ListLeadsStatus = typeof ListLeadsStatus[keyof typeof ListLeadsStatus];


export const ListLeadsStatus = {
  new: 'new',
  contacted: 'contacted',
  converted: 'converted',
  lost: 'lost',
} as const;

