/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Client Lead CRM API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary List all leads
 */
export const ListLeadsQueryParams = zod.object({
  "status": zod.enum(['new', 'contacted', 'converted', 'lost']).optional(),
  "source": zod.coerce.string().optional(),
  "search": zod.coerce.string().optional()
})

export const ListLeadsResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "email": zod.string(),
  "phone": zod.string().nullish(),
  "company": zod.string().nullish(),
  "source": zod.string(),
  "status": zod.enum(['new', 'contacted', 'converted', 'lost']),
  "notes": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})
export const ListLeadsResponse = zod.array(ListLeadsResponseItem)


/**
 * @summary Create a new lead
 */





export const CreateLeadBody = zod.object({
  "name": zod.string().min(1),
  "email": zod.string().min(1),
  "phone": zod.string().optional(),
  "company": zod.string().optional(),
  "source": zod.string().min(1),
  "status": zod.enum(['new', 'contacted', 'converted', 'lost']).optional(),
  "notes": zod.string().optional()
})


/**
 * @summary Get a lead by ID
 */
export const GetLeadParams = zod.object({
  "id": zod.coerce.number()
})

export const GetLeadResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "email": zod.string(),
  "phone": zod.string().nullish(),
  "company": zod.string().nullish(),
  "source": zod.string(),
  "status": zod.enum(['new', 'contacted', 'converted', 'lost']),
  "notes": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string(),
  "leadNotes": zod.array(zod.object({
  "id": zod.number(),
  "leadId": zod.number(),
  "content": zod.string(),
  "followUpDate": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
}))
})


/**
 * @summary Update a lead
 */
export const UpdateLeadParams = zod.object({
  "id": zod.coerce.number()
})





export const UpdateLeadBody = zod.object({
  "name": zod.string().min(1).optional(),
  "email": zod.string().min(1).optional(),
  "phone": zod.string().optional(),
  "company": zod.string().optional(),
  "source": zod.string().optional(),
  "status": zod.enum(['new', 'contacted', 'converted', 'lost']).optional(),
  "notes": zod.string().optional()
})

export const UpdateLeadResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "email": zod.string(),
  "phone": zod.string().nullish(),
  "company": zod.string().nullish(),
  "source": zod.string(),
  "status": zod.enum(['new', 'contacted', 'converted', 'lost']),
  "notes": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})


/**
 * @summary Delete a lead
 */
export const DeleteLeadParams = zod.object({
  "id": zod.coerce.number()
})


/**
 * @summary Update a lead's status
 */
export const UpdateLeadStatusParams = zod.object({
  "id": zod.coerce.number()
})

export const UpdateLeadStatusBody = zod.object({
  "status": zod.enum(['new', 'contacted', 'converted', 'lost'])
})

export const UpdateLeadStatusResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "email": zod.string(),
  "phone": zod.string().nullish(),
  "company": zod.string().nullish(),
  "source": zod.string(),
  "status": zod.enum(['new', 'contacted', 'converted', 'lost']),
  "notes": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})


/**
 * @summary List notes for a lead
 */
export const ListNotesParams = zod.object({
  "id": zod.coerce.number()
})

export const ListNotesResponseItem = zod.object({
  "id": zod.number(),
  "leadId": zod.number(),
  "content": zod.string(),
  "followUpDate": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})
export const ListNotesResponse = zod.array(ListNotesResponseItem)


/**
 * @summary Add a note to a lead
 */
export const CreateNoteParams = zod.object({
  "id": zod.coerce.number()
})




export const CreateNoteBody = zod.object({
  "content": zod.string().min(1),
  "followUpDate": zod.string().optional()
})


/**
 * @summary Update a note
 */
export const UpdateNoteParams = zod.object({
  "noteId": zod.coerce.number()
})




export const UpdateNoteBody = zod.object({
  "content": zod.string().min(1).optional(),
  "followUpDate": zod.string().optional()
})

export const UpdateNoteResponse = zod.object({
  "id": zod.number(),
  "leadId": zod.number(),
  "content": zod.string(),
  "followUpDate": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})


/**
 * @summary Delete a note
 */
export const DeleteNoteParams = zod.object({
  "noteId": zod.coerce.number()
})


/**
 * @summary Get CRM dashboard stats
 */
export const GetDashboardStatsResponse = zod.object({
  "totalLeads": zod.number(),
  "byStatus": zod.object({
  "new": zod.number(),
  "contacted": zod.number(),
  "converted": zod.number(),
  "lost": zod.number()
}),
  "conversionRate": zod.number(),
  "recentCount": zod.number(),
  "bySource": zod.array(zod.object({
  "source": zod.string(),
  "count": zod.number()
})).optional()
})


/**
 * @summary Get recently added or updated leads
 */
export const GetRecentLeadsResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "email": zod.string(),
  "phone": zod.string().nullish(),
  "company": zod.string().nullish(),
  "source": zod.string(),
  "status": zod.enum(['new', 'contacted', 'converted', 'lost']),
  "notes": zod.string().nullish(),
  "createdAt": zod.string(),
  "updatedAt": zod.string()
})
export const GetRecentLeadsResponse = zod.array(GetRecentLeadsResponseItem)


