/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Client Lead CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { LeadInputStatus } from './leadInputStatus';

export interface LeadInput {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  email: string;
  phone?: string;
  company?: string;
  /** @minLength 1 */
  source: string;
  status?: LeadInputStatus;
  notes?: string;
}
