/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Client Lead CRM API
 * OpenAPI spec version: 0.1.0
 */

export type DashboardStatsByStatus = {
  new: number;
  contacted: number;
  converted: number;
  lost: number;
};
