/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Client Lead CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { DashboardStatsBySourceItem } from './dashboardStatsBySourceItem';
import type { DashboardStatsByStatus } from './dashboardStatsByStatus';

export interface DashboardStats {
  totalLeads: number;
  byStatus: DashboardStatsByStatus;
  conversionRate: number;
  recentCount: number;
  bySource?: DashboardStatsBySourceItem[];
}
