/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Client Lead CRM API
 * OpenAPI spec version: 0.1.0
 */
import type { LeadWithNotesStatus } from './leadWithNotesStatus';
import type { Note } from './note';

export interface LeadWithNotes {
  id: number;
  name: string;
  email: string;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  company?: string | null;
  source: string;
  status: LeadWithNotesStatus;
  /** @nullable */
  notes?: string | null;
  createdAt: string;
  updatedAt: string;
  leadNotes: Note[];
}
