/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Client Lead CRM API
 * OpenAPI spec version: 0.1.0
 */

export type LeadStatusUpdateStatus = typeof LeadStatusUpdateStatus[keyof typeof LeadStatusUpdateStatus];


export const LeadStatusUpdateStatus = {
  new: 'new',
  contacted: 'contacted',
  converted: 'converted',
  lost: 'lost',
} as const;
