/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Client Lead CRM API
 * OpenAPI spec version: 0.1.0
 */

export interface Note {
  id: number;
  leadId: number;
  content: string;
  /** @nullable */
  followUpDate?: string | null;
  createdAt: string;
  updatedAt: string;
}
